### ISSUE TITLE
Update document

### ISSUE THREAD

**Issue by chrno1209** [guivic/fastify-bull#2]
Hi,
I see the repo is interesting as I am now trying to integrate Bull into my existing Fastify, can you please update document to see how it works?

**Comment by gustawdaniel** [comment]
Doc is on fork

https://www.npmjs.com/package/fastify-bull

**Comment by lludol** [comment]
@gustawdaniel Can you make a PR ?

**Comment by gustawdaniel** [comment]
I created a pull request for your review @lludol

**Comment by lludol** [comment]
@chrno1209 The doc is updated. I will make more updates this week.
