### ISSUE TITLE
Is connection compatible with bull?

### ISSUE THREAD

**Issue by gustawdaniel** [guivic/fastify-bull#44]
I the constructor of bull Queueu there is no `connection` parameter

```
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queue
```

but in this package, there is `{ connection }` available in options but not documented.

It is probably a bug.

To fix I propose:

```
new Queue(queueName, url)
```

Now bull has types of clients that can or can't share the connection:

- client (can)
- subscriber (can)
- bclient (can't)

described in chapter `Custom or Shared IORedis Connections` of linked docs.

**Comment by lludol** [comment]
@gustawdaniel Hello, I will check after I update the documentation. I will do that today

**Comment by lludol** [comment]
Ok so no there is no parameter Connection as you said (maybe you speak about the fork).
I just updated the doc. There is a RedisUrl parameter. I will add later the "connection" parameter.

Right now I take a RedisUrl paramter to configure automatically the sare IORedis connection.
But, we need to let the user choose what he wants.
